const countryCodes = {
  aed: { rateCode: "aed", name: "UAE dirham" },
  afn: { rateCode: "afn", name: "Afghan afghani" },
  all: { rateCode: "all", name: "Albanian lek" },
  amd: { rateCode: "amd", name: "Armenian dram" },
  ang: { rateCode: "ang", name: "Netherlands Antilles" },
  aoa: { rateCode: "aoa", name: "Angolan kwanza" },
  ars: { rateCode: "ars", name: "Argentine peso" },
  aud: { rateCode: "aud", name: "Australian dollar" },
  awg: { rateCode: "awg", name: "Unknown" },
  azn: { rateCode: "azn", name: "Azerbaijani manat" },
  bam: { rateCode: "bam", name: "	Bosnia and Herzegovina convertible mark" },
  bbd: { rateCode: "bbd", name: "Barbadian dollar" },
  bdt: { rateCode: "bdt", name: "Bangladeshi taka" },
  bgn: { rateCode: "bgn", name: "Bulgarian lev" },
  bhd: { rateCode: "bhd", name: "Bahraini dinar" },
  bif: { rateCode: "bif", name: "Burundian franc" },
  bmd: { rateCode: "bmd", name: "Unknown" },
  bnd: { rateCode: "bnd", name: "Brunei dollar" },
  bob: { rateCode: "bob", name: "Bolivian boliviano" },
  brl: { rateCode: "brl", name: "Brazilian real" },
  bsd: { rateCode: "bsd", name: "Bahamian dollar" },
  btn: { rateCode: "btn", name: "Bhutanese ngultrum" },
  bwp: { rateCode: "bwp", name: "Botswana pula" },
  byn: { rateCode: "byn", name: "Belarusian ruble" },
  bzd: { rateCode: "bzd", name: "Belize dollar" },
  cad: { rateCode: "cad", name: "Canadian dollar" },
  cdf: { rateCode: "cdf", name: "Congolese franc" },
  chf: { rateCode: "chf", name: "Swiss franc" },
  clp: { rateCode: "clp", name: "Chilean peso" },
  cny: { rateCode: "cny", name: "Chinese yuan" },
  cop: { rateCode: "cop", name: "Colombian peso" },
  crc: { rateCode: "crc", name: "Costa Rican colón" },
  cup: { rateCode: "cup", name: "Cuban peso" },
  cve: { rateCode: "cve", name: "Cape Verdean escudo" },
  czk: { rateCode: "czk", name: "Czech koruna" },
  djf: { rateCode: "djf", name: "Djiboutian franc" },
  dkk: { rateCode: "dkk", name: "Danish krone" },
  dop: { rateCode: "dop", name: "Dominican peso" },
  dzd: { rateCode: "dzd", name: "Algerian dinar" },
  egp: { rateCode: "egp", name: "Egyptian pound" },
  ern: { rateCode: "ern", name: "Eritrean nakfa" },
  etb: { rateCode: "etb", name: "Ethiopian birr" },
  eur: { rateCode: "eur", name: "Euro" },
  fjd: { rateCode: "fjd", name: "Fijian dollar" },
  fkp: { rateCode: "fkp", name: "Unknown" },
  fok: { rateCode: "fok", name: "Unknown" },
  gbp: { rateCode: "gbp", name: "British pound" },
  gel: { rateCode: "gel", name: "Georgian lari" },
  ggp: { rateCode: "ggp", name: "Unknown" },
  ghs: { rateCode: "ghs", name: "Ghanaian cedi" },
  gip: { rateCode: "gip", name: "Unknown" },
  gmd: { rateCode: "gmd", name: "Gambian dalasi" },
  gnf: { rateCode: "gnf", name: "Guinean franc" },
  gtq: { rateCode: "gtq", name: "Guatemalan quetzal" },
  gyd: { rateCode: "gyd", name: "Guyanese dollar" },
  hkd: { rateCode: "hkd", name: "Unknown" },
  hnl: { rateCode: "hnl", name: "Honduran lempira" },
  hrk: { rateCode: "hrk", name: "Unknown" },
  htg: { rateCode: "htg", name: "Haitian gourde" },
  huf: { rateCode: "huf", name: "Hungarian forint" },
  idr: { rateCode: "idr", name: "Indonesian rupiah" },
  ils: { rateCode: "ils", name: "Israeli new shekel" },
  imp: { rateCode: "imp", name: "Unknown" },
  inr: { rateCode: "inr", name: "Indian rupee" },
  iqd: { rateCode: "iqd", name: "Iraqi dinar" },
  irr: { rateCode: "irr", name: "Iranian rial" },
  isk: { rateCode: "isk", name: "Icelandic króna" },
  jep: { rateCode: "jep", name: "Unknown" },
  jmd: { rateCode: "jmd", name: "Jamaican dollar" },
  jod: { rateCode: "jod", name: "Jordanian dinar" },
  jpy: { rateCode: "jpy", name: "Japanese yen" },
  kes: { rateCode: "kes", name: "Kenyan shilling" },
  kgs: { rateCode: "kgs", name: "Kyrgyzstani som" },
  khr: { rateCode: "khr", name: "Cambodian riel" },
  kid: { rateCode: "kid", name: "Unknown" },
  kmf: { rateCode: "kmf", name: "Comorian franc" },
  krw: { rateCode: "krw", name: "South Korean won" },
  kwd: { rateCode: "kwd", name: "Kuwaiti dinar" },
  kyd: { rateCode: "kyd", name: "Unknown" },
  kzt: { rateCode: "kzt", name: "Kazakhstani tenge" },
  lak: { rateCode: "lak", name: "Lao kip" },
  lbp: { rateCode: "lbp", name: "Lebanese pound" },
  lkr: { rateCode: "lkr", name: "Sri Lankan rupee" },
  lrd: { rateCode: "lrd", name: "Liberian dollar" },
  lsl: { rateCode: "lsl", name: "Lesotho loti	" },
  lyd: { rateCode: "lyd", name: "Libyan dinar	" },
  mad: { rateCode: "mad", name: "Moroccan dirham" },
  mdl: { rateCode: "mdl", name: "Moldovan leu" },
  mga: { rateCode: "mga", name: "Malagasy ariary" },
  mkd: { rateCode: "mkd", name: "Macedonian denar" },
  mmk: { rateCode: "mmk", name: "Burmese kyat" },
  mnt: { rateCode: "mnt", name: "Mongolian tögrög" },
  mop: { rateCode: "mop", name: "Unknown" },
  mru: { rateCode: "mru", name: "Unknown" },
  mur: { rateCode: "mur", name: "Mauritian rupee" },
  mvr: { rateCode: "mvr", name: "Maldivian rufiyaa" },
  mwk: { rateCode: "mwk", name: "Malawian kwacha" },
  mxn: { rateCode: "mxn", name: "Mexican peso" },
  myr: { rateCode: "myr", name: "Malaysian ringgit" },
  mzn: { rateCode: "mzn", name: "Mozambican metical" },
  nad: { rateCode: "nad", name: "Namibian dollar" },
  ngn: { rateCode: "ngn", name: "Nigerian naira" },
  nio: { rateCode: "nio", name: "	Nicaraguan córdoba" },
  nok: { rateCode: "nok", name: "Norwegian krone" },
  npr: { rateCode: "npr", name: "Nepalese rupee" },
  nzd: { rateCode: "nzd", name: "New Zealand dollar" },
  omr: { rateCode: "omr", name: "Omani rial" },
  pab: { rateCode: "pab", name: "Panamanian balboa" },
  pen: { rateCode: "pen", name: "Peruvian sol" },
  pgk: { rateCode: "pgk", name: "Papua New Guinean kina" },
  php: { rateCode: "php", name: "Philippine peso" },
  pkr: { rateCode: "pkr", name: "Pakistani rupee" },
  pln: { rateCode: "pln", name: "Polish zloty" },
  pyg: { rateCode: "pyg", name: "Paraguayan guaraní" },
  qar: { rateCode: "qar", name: "Qatari riyal" },
  ron: { rateCode: "ron", name: "Romanian leu" },
  rsd: { rateCode: "rsd", name: "Serbian dinar" },
  rub: { rateCode: "rub", name: "Russian ruble" },
  rwf: { rateCode: "rwf", name: "Rwandan franc" },
  sar: { rateCode: "sar", name: "Saudi riyal" },
  sbd: { rateCode: "sbd", name: "Solomon Islands dollar" },
  scr: { rateCode: "scr", name: "Seychellois rupee" },
  sdg: { rateCode: "sdg", name: "Sudanese pound" },
  sek: { rateCode: "sek", name: "Swedish krona" },
  sgd: { rateCode: "sgd", name: "Singapore dollar" },
  shp: { rateCode: "shp", name: "Unknown" },
  sle: { rateCode: "sle", name: "Unknown" },
  sll: { rateCode: "sll", name: "Sierra Leonean leone" },
  sos: { rateCode: "sos", name: "Somali shilling" },
  srd: { rateCode: "srd", name: "Surinamese dollar" },
  ssp: { rateCode: "ssp", name: "South Sudanese pound" },
  stn: { rateCode: "stn", name: "Unknown" },
  syp: { rateCode: "syp", name: "Syrian pound" },
  szl: { rateCode: "szl", name: "Swazi lilangeni" },
  thb: { rateCode: "thb", name: "Thai baht" },
  tjs: { rateCode: "tjs", name: "Tajikistani somoni" },
  tmt: { rateCode: "tmt", name: "Turkmenistan manat" },
  tnd: { rateCode: "tnd", name: "Tunisian dinar" },
  top: { rateCode: "top", name: "Tongan pa'anga" },
  try: { rateCode: "try", name: "Turkish lira" },
  ttd: { rateCode: "ttd", name: "Trinidad and Tobago dollar" },
  tvd: { rateCode: "tvd", name: "Unknown" },
  twd: { rateCode: "twd", name: "New Taiwan dollar" },
  tzs: { rateCode: "tzs", name: "Tanzanian shilling" },
  uah: { rateCode: "uah", name: "Ukrainian hryvnia" },
  ugx: { rateCode: "ugx", name: "Ugandan shilling" },
  usd: { rateCode: "usd", name: "United States dollar" },
  uyu: { rateCode: "uyu", name: "Uruguayan peso" },
  uzs: { rateCode: "uzs", name: "Uzbekistani som" },
  ves: { rateCode: "ves", name: "Unknown" },
  vnd: { rateCode: "vnd", name: "Vietnamese dong" },
  vuv: { rateCode: "vuv", name: "Vanuatu vatu" },
  wst: { rateCode: "wst", name: "Samoan tala" },
  xaf: { rateCode: "xaf", name: "Central African CFA franc" },
  xcd: { rateCode: "xcd", name: "East Caribbean dollar" },
  xdr: { rateCode: "xdr", name: "Unknown" },
  xof: { rateCode: "xof", name: "West African CFA franc" },
  xpf: { rateCode: "xpf", name: "Unknown" },
  yer: { rateCode: "yer", name: "Yemeni rial" },
  zar: { rateCode: "zar", name: "South African rand" },
  zmw: { rateCode: "zmw", name: "Zambian kwacha" },
  zwl: { rateCode: "zwl", name: "Unknown" }
};

export default countryCodes;